In [4]:
!brew install python@3.9

==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: python@3.9 3.9.19 is already installed and up-to-date.
To reinstall 3.9.19, run:
  brew reinstall python@3.9

In [5]:
!which python3.9

/opt/homebrew/bin/python3.9

In [6]:
# Create the virtual environment
!python3.9 -m venv myenv_1

In [7]:
# Upgrade pip to ensure compatibility
!myenv_1/bin/python -m pip install --upgrade pip

Requirement already satisfied: pip in ./myenv_1/lib/python3.9/site-packages (24.0)

In [8]:
!myenv_1/bin/python -m pip install -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt

Collecting pandas==1.5.3 (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 1))
  Using cached pandas-1.5.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting numpy==1.21.0 (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 2))
  Downloading numpy-1.21.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (2.0 kB)
Collecting protobuf==4.21.6 (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 3))
  Using cached protobuf-4.21.6-cp37-abi3-macosx_10_9_universal2.whl.metadata (540 bytes)
Collecting scikit_learn==1.1.2 (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 4))
  Using cached scikit_learn-1.1.2-cp39-cp39-macosx_12_0_arm64.whl.metadata (10 kB)
Collecting setuptools==59.8.0 (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 5))
  Using cached setuptools-59.8.0-py3-none-any.whl.metadata (5.0 kB)
Collecting gcsfs>=2021.4.0 (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached gcsfs-2024.6.0-py2.py3-none-any.whl.metadata (1.6 kB)
Collecting python-dotenv (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 8))
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting xgboost (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 9))
  Using cached xgboost-2.0.3-py3-none-macosx_12_0_arm64.whl.metadata (2.0 kB)
Collecting Flask (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting joblib (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 11))
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting google-cloud-logging (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached google_cloud_logging-3.10.0-py2.py3-none-any.whl.metadata (4.9 kB)
Collecting google-auth (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 14))
  Using cached google_auth-2.30.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting google-cloud-bigquery (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 15))
  Using cached google_cloud_bigquery-3.24.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting google-cloud-storage (from -r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 16))
  Using cached google_cloud_storage-2.17.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.1 (from pandas==1.5.3->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 1))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==1.5.3->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 1))
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting scipy>=1.3.2 (from scikit_learn==1.1.2->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 4))
  Using cached scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
Collecting threadpoolctl>=2.0.0 (from scikit_learn==1.1.2->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 4))
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached aiohttp-3.9.5-cp39-cp39-macosx_11_0_arm64.whl.metadata (7.5 kB)
Collecting decorator>4.1.2 (from gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting fsspec==2024.6.0 (from gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached fsspec-2024.6.0-py3-none-any.whl.metadata (11 kB)
Collecting google-auth-oauthlib (from gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached google_auth_oauthlib-1.2.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting requests (from gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting Werkzeug>=3.0.0 (from Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached werkzeug-3.0.3-py3-none-any.whl.metadata (3.7 kB)
Collecting Jinja2>=3.1.2 (from Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.1.2 (from Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting click>=8.1.3 (from Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached blinker-1.8.2-py3-none-any.whl.metadata (1.6 kB)
Collecting importlib-metadata>=3.6.0 (from Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached google_api_core-2.19.0-py3-none-any.whl.metadata (2.7 kB)
Collecting google-cloud-appengine-logging<2.0.0dev,>=0.1.0 (from google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached google_cloud_appengine_logging-1.4.3-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting google-cloud-audit-log<1.0.0dev,>=0.1.0 (from google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached google_cloud_audit_log-0.2.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting google-cloud-core<3.0.0dev,>=2.0.0 (from google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached google_cloud_core-2.4.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting grpc-google-iam-v1<1.0.0dev,>=0.12.4 (from google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached grpc_google_iam_v1-0.13.0-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting proto-plus<2.0.0dev,>=1.22.0 (from google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached proto_plus-1.23.0-py3-none-any.whl.metadata (2.2 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 14))
  Using cached cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 14))
  Using cached pyasn1_modules-0.4.0-py3-none-any.whl.metadata (3.4 kB)
Collecting rsa<5,>=3.1.4 (from google-auth->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 14))
  Using cached rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting google-resumable-media<3.0dev,>=0.6.0 (from google-cloud-bigquery->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 15))
  Using cached google_resumable_media-2.7.1-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting packaging>=20.0.0 (from google-cloud-bigquery->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 15))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting google-crc32c<2.0dev,>=1.0 (from google-cloud-storage->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 16))
  Using cached google_crc32c-1.5.0-cp39-cp39-macosx_10_9_universal2.whl.metadata (2.3 kB)
Collecting aiosignal>=1.1.2 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached frozenlist-1.4.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached multidict-6.0.5-cp39-cp39-macosx_11_0_arm64.whl.metadata (4.2 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached yarl-1.9.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (31 kB)
Collecting async-timeout<5.0,>=4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached googleapis_common_protos-1.63.1-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting grpcio<2.0dev,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached grpcio-1.64.1-cp39-cp39-macosx_10_9_universal2.whl.metadata (3.3 kB)
Collecting grpcio-status<2.0.dev0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached grpcio_status-1.64.1-py3-none-any.whl.metadata (1.1 kB)
Collecting zipp>=0.5 (from importlib-metadata>=3.6.0->Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached zipp-3.19.2-py3-none-any.whl.metadata (3.6 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1.2->Flask->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 10))
  Using cached MarkupSafe-2.1.5-cp39-cp39-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 14))
  Using cached pyasn1-0.6.0-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.1->pandas==1.5.3->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 1))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting charset-normalizer<4,>=2 (from requests->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached charset_normalizer-3.3.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached certifi-2024.6.2-py3-none-any.whl.metadata (2.2 kB)
INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
Collecting scipy>=1.3.2 (from scikit_learn==1.1.2->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 4))
  Downloading scipy-1.13.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.2 MB/s eta 0:00:00ta 0:00:01
  Downloading scipy-1.12.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.7 MB/s eta 0:00:00
  Downloading scipy-1.11.4-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.8 MB/s eta 0:00:00
  Downloading scipy-1.11.3-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.2 MB/s eta 0:00:00a 0:00:01
  Downloading scipy-1.11.2-cp39-cp39-macosx_12_0_arm64.whl.metadata (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.1/54.1 kB 2.1 MB/s eta 0:00:00
  Downloading scipy-1.11.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.1/54.1 kB 1.8 MB/s eta 0:00:00
  Downloading scipy-1.10.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 kB 1.6 MB/s eta 0:00:00
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.dev0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-logging->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 13))
  Using cached grpcio_status-1.64.0-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.63.0-py3-none-any.whl.metadata (1.1 kB)
  Using cached grpcio_status-1.62.2-py3-none-any.whl.metadata (1.3 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs>=2021.4.0->-r /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/requirement.txt (line 6))
  Using cached oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Using cached pandas-1.5.3-cp39-cp39-macosx_11_0_arm64.whl (11.0 MB)
Downloading numpy-1.21.0-cp39-cp39-macosx_11_0_arm64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 4.8 MB/s eta 0:00:0000:0100:01
Using cached protobuf-4.21.6-cp37-abi3-macosx_10_9_universal2.whl (484 kB)
Using cached scikit_learn-1.1.2-cp39-cp39-macosx_12_0_arm64.whl (7.7 MB)
Using cached setuptools-59.8.0-py3-none-any.whl (952 kB)
Using cached gcsfs-2024.6.0-py2.py3-none-any.whl (34 kB)
Using cached fsspec-2024.6.0-py3-none-any.whl (176 kB)
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached xgboost-2.0.3-py3-none-macosx_12_0_arm64.whl (1.9 MB)
Using cached flask-3.0.3-py3-none-any.whl (101 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached google_cloud_logging-3.10.0-py2.py3-none-any.whl (213 kB)
Using cached google_auth-2.30.0-py2.py3-none-any.whl (193 kB)
Using cached google_cloud_bigquery-3.24.0-py2.py3-none-any.whl (238 kB)
Using cached google_cloud_storage-2.17.0-py2.py3-none-any.whl (126 kB)
Using cached aiohttp-3.9.5-cp39-cp39-macosx_11_0_arm64.whl (390 kB)
Using cached blinker-1.8.2-py3-none-any.whl (9.5 kB)
Using cached cachetools-5.3.3-py3-none-any.whl (9.3 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Using cached google_api_core-2.19.0-py3-none-any.whl (139 kB)
Using cached google_cloud_appengine_logging-1.4.3-py2.py3-none-any.whl (15 kB)
Using cached google_cloud_audit_log-0.2.5-py2.py3-none-any.whl (12 kB)
Using cached google_cloud_core-2.4.1-py2.py3-none-any.whl (29 kB)
Using cached google_crc32c-1.5.0-cp39-cp39-macosx_10_9_universal2.whl (32 kB)

In [9]:
# Install ipykernel in the virtual environment
!myenv_1/bin/python -m pip install ipykernel

Collecting ipykernel
  Using cached ipykernel-6.29.4-py3-none-any.whl.metadata (6.3 kB)
Collecting appnope (from ipykernel)
  Using cached appnope-0.1.4-py2.py3-none-any.whl.metadata (908 bytes)
Collecting comm>=0.1.1 (from ipykernel)
  Using cached comm-0.2.2-py3-none-any.whl.metadata (3.7 kB)
Collecting debugpy>=1.6.5 (from ipykernel)
  Using cached debugpy-1.8.1-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting ipython>=7.23.1 (from ipykernel)
  Using cached ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Collecting jupyter-client>=6.1.12 (from ipykernel)
  Using cached jupyter_client-8.6.2-py3-none-any.whl.metadata (8.3 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from ipykernel)
  Using cached jupyter_core-5.7.2-py3-none-any.whl.metadata (3.4 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel)
  Using cached matplotlib_inline-0.1.7-py3-none-any.whl.metadata (3.9 kB)
Collecting nest-asyncio (from ipykernel)
  Using cached nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: packaging in ./myenv_1/lib/python3.9/site-packages (from ipykernel) (24.1)
Collecting psutil (from ipykernel)
  Using cached psutil-5.9.8-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting pyzmq>=24 (from ipykernel)
  Using cached pyzmq-26.0.3-cp39-cp39-macosx_10_15_universal2.whl.metadata (6.1 kB)
Collecting tornado>=6.1 (from ipykernel)
  Using cached tornado-6.4.1-cp38-abi3-macosx_10_9_universal2.whl.metadata (2.5 kB)
Collecting traitlets>=5.4.0 (from ipykernel)
  Using cached traitlets-5.14.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: decorator in ./myenv_1/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.41 (from ipython>=7.23.1->ipykernel)
  Using cached prompt_toolkit-3.0.47-py3-none-any.whl.metadata (6.4 kB)
Collecting pygments>=2.4.0 (from ipython>=7.23.1->ipykernel)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting stack-data (from ipython>=7.23.1->ipykernel)
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting typing-extensions (from ipython>=7.23.1->ipykernel)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting exceptiongroup (from ipython>=7.23.1->ipykernel)
  Using cached exceptiongroup-1.2.1-py3-none-any.whl.metadata (6.6 kB)
Collecting pexpect>4.3 (from ipython>=7.23.1->ipykernel)
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: importlib-metadata>=4.8.3 in ./myenv_1/lib/python3.9/site-packages (from jupyter-client>=6.1.12->ipykernel) (7.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./myenv_1/lib/python3.9/site-packages (from jupyter-client>=6.1.12->ipykernel) (2.9.0.post0)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->ipykernel)
  Using cached platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: zipp>=0.5 in ./myenv_1/lib/python3.9/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=6.1.12->ipykernel) (3.19.2)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython>=7.23.1->ipykernel)
  Using cached parso-0.8.4-py2.py3-none-any.whl.metadata (7.7 kB)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython>=7.23.1->ipykernel)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting wcwidth (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: six>=1.5 in ./myenv_1/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.16.0)
Collecting executing>=1.2.0 (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached pure_eval-0.2.2-py3-none-any.whl.metadata (6.2 kB)
Using cached ipykernel-6.29.4-py3-none-any.whl (117 kB)
Using cached comm-0.2.2-py3-none-any.whl (7.2 kB)
Using cached debugpy-1.8.1-py2.py3-none-any.whl (4.8 MB)
Using cached ipython-8.18.1-py3-none-any.whl (808 kB)
Using cached jupyter_client-8.6.2-py3-none-any.whl (105 kB)
Using cached jupyter_core-5.7.2-py3-none-any.whl (28 kB)
Using cached matplotlib_inline-0.1.7-py3-none-any.whl (9.9 kB)
Using cached pyzmq-26.0.3-cp39-cp39-macosx_10_15_universal2.whl (1.4 MB)
Using cached tornado-6.4.1-cp38-abi3-macosx_10_9_universal2.whl (435 kB)
Using cached traitlets-5.14.3-py3-none-any.whl (85 kB)
Using cached appnope-0.1.4-py2.py3-none-any.whl (4.3 kB)
Using cached nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Using cached psutil-5.9.8-cp38-abi3-macosx_11_0_arm64.whl (249 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached platformdirs-4.2.2-py3-none-any.whl (18 kB)
Using cached prompt_toolkit-3.0.47-py3-none-any.whl (386 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached parso-0.8.4-py2.py3-none-any.whl (103 kB)
Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Installing collected packages: wcwidth, pure-eval, ptyprocess, typing-extensions, traitlets, tornado, pyzmq, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, nest-asyncio, executing, exceptiongroup, debugpy, asttokens, appnope, stack-data, matplotlib-inline, jupyter-core, jedi, comm, jupyter-client, ipython, ipykernel
Successfully installed appnope-0.1.4 asttokens-2.4.1 comm-0.2.2 debugpy-1.8.1 exceptiongroup-1.2.1 executing-2.0.1 ipykernel-6.29.4 ipython-8.18.1 jedi-0.19.1 jupyter-client-8.6.2 jupyter-core-5.7.2 matplotlib-inline-0.1.7 nest-asyncio-1.6.0 parso-0.8.4 pexpect-4.9.0 platformdirs-4.2.2 prompt-toolkit-3.0.47 psutil-5.9.8 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.18.0 pyzmq-26.0.3 stack-data-0.6.3 tornado-6.4.1 traitlets-5.14.3 typing-extensions-4.12.2 wcwidth-0.2.13

In [10]:
# Add the virtual environment as a Jupyter kernel
!myenv_1/bin/python -m ipykernel install --user --name=myenv_1 --display-name "Python (myenv_1)"

Installed kernelspec myenv_1 in /Users/rishabkhuba/Library/Jupyter/kernels/myenv_1

In [11]:
# List all Jupyter kernels
!jupyter kernelspec list

Available kernels:
  myenv              /Users/rishabkhuba/Library/Jupyter/kernels/myenv
  myenv_1            /Users/rishabkhuba/Library/Jupyter/kernels/myenv_1
  old_sklearn_env    /Users/rishabkhuba/Library/Jupyter/kernels/old_sklearn_env
  tensorflow         /Users/rishabkhuba/Library/Jupyter/kernels/tensorflow
  python3            /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/myenv_1/share/jupyter/kernels/python3

In [1]:
import numpy as np 

print(np.__version__)

1.21.0

In [108]:
import sys
import numpy as np
import pandas as pd
import pickle
import os

print("Python executable:", sys.executable)
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

Python executable: /Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/myenv_1/bin/python
NumPy version: 1.21.0
Pandas version: 1.5.3

In [109]:
model_path = "/Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/models/model-run-20240617-014341/model.pkl"
scalar_path = "/Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/artifact/scaler.pkl"

In [110]:
def load_data_from_pickle(file_path):
    with open(file_path, 'rb') as file:
        data = pickle.load(file)
    return data

In [174]:
def read_data(filepath, df):
    """
    Reusable function to read PSV data from source directory.
    
    Parameters:
        filepath (str): The path to the directory containing PSV files.
        df (pd.DataFrame): The DataFrame to append the read data to.
        
    Returns:
        pd.DataFrame: The DataFrame containing all the read data.
    """
    count = 0
    rows = 0
    data_frames = []
    
    for filename in os.listdir(filepath):
        if filename.endswith(".psv"):
            with open(filepath + filename) as openfile:
                patient = filename.split("p")[1]
                patient = patient.split(".")[0]

                file = pd.read_csv(openfile, sep="|")
                file['Patient_ID'] = patient
                
                file = file.reset_index()
                file = file.rename(columns={"index": "Hour"})
                print(file)
                
                data_frames.append(file)
                rows += file.shape[0]
                count += 1
                
        # Print progress after 10k files
        if count % 10000 == 0:
            print("Progress || Files: {} || Number of items: {}".format(count, rows))
    
    # Concatenate all collected DataFrames
    df = pd.concat(data_frames, ignore_index=True)
    
    print("Done ||| Files: {} || Number of items: {}".format(count, rows))
    return df

# Example usage
filepath = '/Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_experiment/batch_test_3/'  # Replace with your actual filepath
df = pd.DataFrame()  # Initial empty DataFrame
dataset = read_data(filepath, df)

    Hour     HR  O2Sat  Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  \
0      0    NaN    NaN   NaN    NaN    NaN   NaN   NaN    NaN         NaN
1      1   86.0   99.0   NaN  141.0   93.0  80.0  16.0    NaN         NaN
2      2   85.0   94.0   NaN  143.0   98.0  84.0  19.0    NaN         NaN
3      3   85.0  100.0   NaN  125.0   81.0  67.0  19.0    NaN         NaN
4      4   89.0   98.0   NaN  136.0   91.0  76.0  18.0    NaN         NaN
5      5   84.0   97.0  37.2  123.0   87.0  75.0  19.0    NaN         NaN
6      6   90.0  100.0   NaN  142.0   98.0  84.0  16.0    NaN         NaN
7      7   89.0  100.0   NaN  148.0   99.0  83.0  18.0    NaN         NaN
8      8   92.0   99.0   NaN  148.0   95.0  79.0  18.0    NaN         NaN
9      9   92.0   98.0  36.8  141.0   94.0  79.0   8.0    NaN         NaN
10    10   99.0   97.0   NaN  155.0  104.0  86.0  11.0    NaN         NaN
11    11   91.0   97.0   NaN  160.0  104.0  87.0  15.0    NaN         NaN
12    12  100.0   98.0   NaN  161.0  105.0  88.0  18.0    NaN         NaN
13    13   94.0  100.0  36.8  163.0  111.0  93.0  15.0    NaN         NaN
14    14  105.0  100.0   NaN  171.0  117.0  99.0  16.0    NaN         NaN
15    15  101.0  100.0   NaN  149.0  106.0  94.0  15.0    NaN         NaN

    ...  Fibrinogen  Platelets  Age  Gender  Unit1  Unit2  HospAdmTime  \
0   ...         NaN        NaN   32       0      1      0        -8.13
1   ...         NaN        NaN   32       0      1      0        -8.13
2   ...         NaN        NaN   32       0      1      0        -8.13
3   ...         NaN        NaN   32       0      1      0        -8.13
4   ...         NaN        NaN   32       0      1      0        -8.13
5   ...         NaN        NaN   32       0      1      0        -8.13
6   ...         NaN        NaN   32       0      1      0        -8.13
7   ...         NaN        NaN   32       0      1      0        -8.13
8   ...         NaN        NaN   32       0      1      0        -8.13
9   ...         NaN        NaN   32       0      1      0        -8.13
10  ...         NaN        NaN   32       0      1      0        -8.13
11  ...         NaN        NaN   32       0      1      0        -8.13
12  ...         NaN        NaN   32       0      1      0        -8.13
13  ...         NaN        NaN   32       0      1      0        -8.13
14  ...         NaN        NaN   32       0      1      0        -8.13
15  ...         NaN        NaN   32       0      1      0        -8.13

    ICULOS  SepsisLabel  Patient_ID
0        1            0      100010
1        2            0      100010
2        3            0      100010
3        4            0      100010
4        5            0      100010
5        6            0      100010
6        7            0      100010
7        8            0      100010
8        9            0      100010
9       10            0      100010
10      11            0      100010
11      12            0      100010
12      13            0      100010
13      14            0      100010
14      15            0      100010
15      16            0      100010

[16 rows x 43 columns]
    Hour     HR  O2Sat  Temp    SBP    MAP    DBP  Resp  EtCO2  BaseExcess  \
0      0    NaN    NaN   NaN    NaN    NaN    NaN   NaN    NaN         NaN
1      1   65.0  100.0   NaN  140.0   84.0   65.0  14.0    NaN         NaN
2      2    NaN    NaN   NaN    NaN    NaN    NaN   NaN    NaN         NaN
3      3   64.0  100.0   NaN    NaN    NaN    NaN   NaN    NaN         NaN
4      4   65.0  100.0   NaN  125.0   68.0   64.0  12.0    NaN         NaN
5      5   68.5  100.0  36.7  126.0   76.0   61.0  12.5    NaN         NaN
6      6   68.0    NaN   NaN  122.0   75.0   57.0   NaN    NaN         NaN
7      7   68.0  100.0   NaN  122.0   74.0   58.0   NaN    NaN         NaN
8      8   68.0  100.0   NaN  121.0   73.0   56.0  14.0    NaN         NaN
9      9   68.0  100.0  37.3  125.0   78.0   62.0  13.0    NaN         NaN
10    10   69.0  100.0   NaN  123.0   77.0   62.0  13.0    NaN         NaN
11    11   70.0  100.0   NaN  119.0   74.0   59.0  13.0    NaN         NaN
12    12   75.0  100.0   NaN  130.0   79.0   63.0  12.0    NaN         NaN
13    13   75.0  100.0  37.7  123.0   77.0   62.0  10.0    NaN         NaN
14    14   76.0  100.0   NaN  120.0   76.0   61.0  10.0    NaN         NaN
15    15   74.0  100.0  37.7  113.5   77.0   61.5  16.0    NaN         NaN
16    16   76.0  100.0   NaN  135.0   82.0   66.0  12.0    NaN         NaN
17    17   77.0  100.0   NaN  128.0   76.0   58.0  14.0    NaN         NaN
18    18   78.5  100.0  37.8  130.0   77.0   60.0  14.5    NaN         NaN
19    19   80.0  100.0   NaN  128.0   75.0   59.0  12.0    NaN         NaN
20    20   83.0  100.0   NaN  137.0   79.0   60.0  16.0    NaN         NaN
21    21   85.0  100.0  37.6  136.0   80.0   63.0  17.0    NaN         NaN
22    22   84.0  100.0   NaN  121.0   78.0   63.0  15.0    NaN         NaN
23    23   85.0  100.0   NaN  126.0   75.0   59.0  12.0    NaN         NaN
24    24   85.0  100.0   NaN  136.0   83.0   65.0  16.0    NaN         NaN
25    25   87.0  100.0  37.9  141.0   85.0   65.0   NaN    NaN         NaN
26    26   82.0  100.0   NaN  127.0   76.0   60.0   NaN    NaN         NaN
27    27   83.0  100.0   NaN  101.0   64.0   52.0   NaN    NaN         NaN
28    28   91.0  100.0   NaN  144.0   87.0   69.0  10.0    NaN         NaN
29    29   86.0   99.0  38.0  119.0   70.0   55.0  10.0    NaN         NaN
30    30   85.0  100.0   NaN  140.0   87.0   64.0  10.0    NaN         NaN
31    31   92.0  100.0   NaN  122.0   76.0   61.0  10.0    NaN         NaN
32    32   84.0  100.0   NaN  133.0   85.0   67.0  10.0    NaN         NaN
33    33   83.0  100.0  37.8  132.0   80.0   64.0  10.0    NaN         NaN
34    34   83.0  100.0   NaN  145.0   93.0   77.0  10.0    NaN         NaN
35    35   86.0  100.0   NaN  139.0   86.0   69.0  10.0    NaN         NaN
36    36   87.0  100.0   NaN  160.0   97.0   80.0  10.0    NaN         NaN
37    37   91.0  100.0  37.4  156.0   95.0   74.0  10.0    NaN         NaN
38    38   93.0  100.0   NaN  158.0  106.0   90.0  10.0    NaN         NaN
39    39   86.0  100.0   NaN  150.0   85.0   67.0  10.0    NaN         NaN
40    40  125.0  100.0   NaN  118.0   86.0   74.0  13.0    NaN         NaN
41    41  124.0  100.0   NaN    NaN    NaN    NaN  12.0    NaN         NaN
42    42  130.0  100.0  37.5  133.5   89.0   76.5  12.0    NaN         NaN
43    43  122.0  100.0   NaN  147.0   96.0   85.0  10.0    NaN         NaN
44    44  110.0  100.0   NaN  132.0   84.0   67.0  13.0    NaN         NaN
45    45  114.0  100.0  37.7  137.0   90.0   77.0  12.0    NaN         NaN
46    46  118.0  100.0   NaN  131.0   86.0   70.0  10.0    NaN         NaN
47    47  118.0  100.0   NaN  146.0   98.0   72.0  12.0    NaN         NaN
48    48  119.0  100.0   NaN  130.0  120.0  104.0  11.0    NaN         NaN
49    49  117.0  100.0  37.6  146.0  100.0   85.0  13.0    NaN         NaN
50    50  115.0   96.0   NaN  127.0   92.0   80.0  12.0    NaN         NaN
51    51  119.0   99.0   NaN  142.0   95.0   82.0  11.0    NaN         NaN
52    52  109.0  100.0   NaN  147.0   98.0   79.0   NaN    NaN         NaN
53    53  116.5  100.0  37.7  159.0  102.0   85.0  13.0    NaN         NaN
54    54  112.0  100.0   NaN  148.0   93.0   74.0  11.0    NaN         NaN
55    55  109.0  100.0   NaN  150.0   96.0   79.0  10.0    NaN         NaN
56    56  108.0  100.0   NaN  128.0   89.0   76.0  12.0    NaN         NaN
57    57  108.0  100.0   NaN  160.0  100.0   81.0  12.0    NaN         NaN
58    58  112.0  100.0   NaN  152.0  111.0   98.0  11.0    NaN         NaN

    ...  Fibrinogen  Platelets  Age  Gender  Unit1  Unit2  HospAdmTime  \
0   ...         NaN        NaN   67       1      1      0        -1.93
1   ...         NaN        NaN   67       1      1      0        -1.93
2   ...         NaN        NaN   67       1      1      0        -1.93
3   ...         NaN        NaN   67       1      1      0        -1.93
4   ...         NaN        NaN   67       1      1      0        -1.93
5   ...         NaN        NaN   67       1      1      0        -1.93
6   ...         NaN        NaN   67       1      1      0        -1.93
7   ...         NaN        NaN   67       1      1      0        -1.93
8   ...         NaN        NaN   67       1      1      0        -1.93
9   ...         NaN        NaN   67       1      1      0        -1.93
10  ...         NaN        NaN   67       1      1      0        -1.93
11  ...         NaN        NaN   67       1      1      0        -1.93
12  ...         NaN        NaN   67       1      1      0        -1.93
13  ...         NaN        NaN   67       1      1      0        -1.93
14  ...         NaN        NaN   67       1      1      0        -1.93
15  ...         NaN        NaN   67       1      1      0        -1.93
16  ...         NaN        NaN   67       1      1      0        -1.93
17  ...         NaN        NaN   67       1      1      0        -1.93
18  ...         NaN        NaN   67       1      1      0        -1.93
19  ...         NaN        NaN   67       1      1      0        -1.93
20  ...         NaN        NaN   67       1      1      0        -1.93
21  ...         NaN        NaN   67       1      1      0        -1.93
22  ...         NaN        NaN   67       1      1      0        -1.93
23  ...         NaN        NaN   67       1      1      0        -1.93
24  ...         NaN        NaN   67       1      1      0        -1.93
25  ...         NaN        NaN   67       1      1      0        -1.93
26  ...         NaN        NaN   67       1      1      0        -1.93
27  ...         NaN        NaN   67       1      1      0        -1.93
28  ...         NaN        NaN   67       1      1      0        -1.93
29  ...         NaN        NaN   67       1      1      0        -1.93
30  ...         NaN        NaN   67       1      1      0        -1.93
31  ...         NaN        NaN   67       1      1      0        -1.93
32  ...         NaN        NaN   67       1      1      0        -1.93
33  ...         NaN        NaN   67       1      1      0        -1.93
34  ...         NaN        NaN   67       1      1      0        -1.93
35  ...         NaN        NaN   67       1      1      0        -1.93
36  ...         NaN        NaN   67       1      1      0        -1.93
37  ...         NaN        NaN   67       1      1      0        -1.93
38  ...         NaN        NaN   67       1      1      0        -1.93
39  ...         NaN        NaN   67       1      1      0        -1.93
40  ...         NaN        NaN   67       1      1      0        -1.93
41  ...         NaN        NaN   67       1      1      0        -1.93
42  ...         NaN        NaN   67       1      1      0        -1.93
43  ...         NaN        NaN   67       1      1      0        -1.93
44  ...         NaN        NaN   67       1      1      0        -1.93
45  ...         NaN        NaN   67       1      1      0        -1.93
46  ...         NaN        NaN   67       1      1      0        -1.93
47  ...         NaN        NaN   67       1      1      0        -1.93
48  ...         NaN        NaN   67       1      1      0        -1.93
49  ...         NaN        NaN   67       1      1      0        -1.93
50  ...         NaN        NaN   67       1      1      0        -1.93
51  ...         NaN        NaN   67       1      1      0        -1.93
52  ...         NaN        NaN   67       1      1      0        -1.93
53  ...         NaN        NaN   67       1      1      0        -1.93
54  ...         NaN        NaN   67       1      1      0        -1.93
55  ...         NaN        NaN   67       1      1      0        -1.93
56  ...         NaN        NaN   67       1      1      0        -1.93
57  ...         NaN        NaN   67       1      1      0        -1.93
58  ...         NaN        NaN   67       1      1      0        -1.93

    ICULOS  SepsisLabel  Patient_ID
0        1            0      100004
1        2            0      100004
2        3            0      100004
3        4            0      100004
4        5            0      100004
5        6            0      100004
6        7            0      100004
7        8            0      100004
8        9            0      100004
9       10            0      100004
10      11            0      100004
11      12            0      100004
12      13            0      100004
13      14            0      100004
14      15            0      100004
15      16            0      100004
16      17            0      100004
17      18            0      100004
18      19            0      100004
19      20            0      100004
20      21            0      100004
21      22            0      100004
22      23            0      100004
23      24            0      100004
24      25            0      100004
25      26            0      100004
26      27            0      100004
27      28            0      100004
28      29            0      100004
29      30            0      100004
30      31            0      100004
31      32            0      100004
32      33            0      100004
33      34            0      100004
34      35            0      100004
35      36            0      100004
36      37            0      100004
37      38            0      100004
38      39            0      100004
39      40            0      100004
40      41            0      100004
41      42            0      100004
42      43            0      100004
43      44            0      100004
44      45            0      100004
45      46            0      100004
46      47            0      100004
47      48            0      100004
48      49            0      100004
49      50            0      100004
50      51            0      100004
51      52            0      100004
52      53            0      100004
53      54            0      100004
54      55            0      100004
55      56            0      100004
56      57            0      100004
57      58            0      100004
58      59            0      100004

[59 rows x 43 columns]
    Hour    HR  O2Sat  Temp    SBP    MAP    DBP  Resp  EtCO2  BaseExcess  \
0      0   NaN    NaN   NaN    NaN    NaN    NaN   NaN    NaN         NaN
1      1  68.0   98.0  38.3  122.5   72.5   56.5   NaN    NaN         NaN
2      2  75.0   99.0   NaN  144.5  101.0   89.5   NaN    NaN         NaN
3      3  70.0   99.0  37.3  126.0   76.5   59.5  19.0    NaN         NaN
4      4  66.0  100.0   NaN    NaN    NaN    NaN   NaN    NaN         NaN
5      5  66.0    NaN   NaN  142.0   80.0   63.0  13.0    NaN         NaN
6      6  66.0  100.0  36.1  127.0   76.5   65.0   NaN    NaN         NaN
7      7  73.0    NaN   NaN  137.0   79.0   59.0  20.0    NaN         NaN
8      8  67.0   99.0   NaN  117.0  101.0   98.0   NaN    NaN         NaN
9      9  71.5  100.0   NaN  152.5   95.5   78.5   NaN    NaN         NaN
10    10  83.0   98.5   NaN  156.5  101.0   87.5  19.0    NaN         NaN
11    11  82.0    NaN   NaN  173.0  100.0   75.0  20.0    NaN         NaN
12    12  73.0   97.0   NaN  149.0   88.0   68.0  18.0    NaN         NaN
13    13  78.0    NaN  36.4  156.0   90.0   69.0  20.0    NaN         NaN
14    14  69.0    NaN   NaN  120.0   71.0   58.0  18.0    NaN         NaN
15    15  63.0    NaN   NaN  136.0   76.0   58.0  20.0    NaN         NaN
16    16  64.0    NaN   NaN  133.0   77.0   59.0  20.0    NaN         NaN
17    17  63.0    NaN   NaN  134.0   79.0   63.0  18.0    NaN         NaN
18    18  80.0   98.0   NaN  158.0   88.0   63.0  18.0    NaN         NaN
19    19   NaN    NaN   NaN    NaN    NaN    NaN   NaN    NaN         NaN
20    20  68.0   99.0   NaN  136.0   80.0   61.0   NaN    NaN         NaN
21    21  74.0   97.0  37.4  143.0   86.0   67.0  20.0    NaN         NaN
22    22  72.0   97.0   NaN  143.0  106.0   95.0   NaN    NaN         NaN
23    23  72.0   99.0   NaN  142.0   81.0   63.0  16.5    NaN         NaN
24    24  70.0   95.0   NaN  139.0  106.0   98.0  21.0    NaN         NaN
25    25  77.0   96.0  36.8  146.0   85.0   65.0  17.0    NaN         NaN
26    26  76.0   98.0   NaN  155.0   89.0   68.0  18.0    NaN         NaN
27    27  77.0   98.0   NaN  130.0  116.0  113.0  19.0    NaN         NaN
28    28  68.0    NaN   NaN  142.0   83.0   64.0   NaN    NaN         NaN
29    29  66.0    NaN   NaN  142.0   83.0   64.0  17.0    NaN         NaN
30    30  68.0   99.0  36.9  129.0  108.0  102.0  18.0    NaN         NaN

    ...  Fibrinogen  Platelets  Age  Gender  Unit1  Unit2  HospAdmTime  \
0   ...         NaN        NaN   67       1    NaN    NaN      -212.74
1   ...         NaN        NaN   67       1    NaN    NaN      -212.74
2   ...         NaN        NaN   67       1    NaN    NaN      -212.74
3   ...         NaN        NaN   67       1    NaN    NaN      -212.74
4   ...         NaN        NaN   67       1    NaN    NaN      -212.74
5   ...         NaN        NaN   67       1    NaN    NaN      -212.74
6   ...         NaN        NaN   67       1    NaN    NaN      -212.74
7   ...         NaN        NaN   67       1    NaN    NaN      -212.74
8   ...         NaN        NaN   67       1    NaN    NaN      -212.74
9   ...         NaN        NaN   67       1    NaN    NaN      -212.74
10  ...         NaN        NaN   67       1    NaN    NaN      -212.74
11  ...         NaN        NaN   67       1    NaN    NaN      -212.74
12  ...         NaN        NaN   67       1    NaN    NaN      -212.74
13  ...         NaN        NaN   67       1    NaN    NaN      -212.74
14  ...         NaN        NaN   67       1    NaN    NaN      -212.74
15  ...         NaN        NaN   67       1    NaN    NaN      -212.74
16  ...         NaN        NaN   67       1    NaN    NaN      -212.74
17  ...         NaN        NaN   67       1    NaN    NaN      -212.74
18  ...         NaN        NaN   67       1    NaN    NaN      -212.74
19  ...         NaN        NaN   67       1    NaN    NaN      -212.74
20  ...         NaN        NaN   67       1    NaN    NaN      -212.74
21  ...         NaN        NaN   67       1    NaN    NaN      -212.74
22  ...         NaN        NaN   67       1    NaN    NaN      -212.74
23  ...         NaN      356.0   67       1    NaN    NaN      -212.74
24  ...         NaN        NaN   67       1    NaN    NaN      -212.74
25  ...         NaN        NaN   67       1    NaN    NaN      -212.74
26  ...         NaN        NaN   67       1    NaN    NaN      -212.74
27  ...         NaN        NaN   67       1    NaN    NaN      -212.74
28  ...         NaN        NaN   67       1    NaN    NaN      -212.74
29  ...         NaN        NaN   67       1    NaN    NaN      -212.74
30  ...         NaN        NaN   67       1    NaN    NaN      -212.74

    ICULOS  SepsisLabel  Patient_ID
0        1            0      100038
1        2            0      100038
2        3            0      100038
3        4            0      100038
4        5            0      100038
5        6            0      100038
6        7            0      100038
7        8            0      100038
8        9            0      100038
9       10            0      100038
10      11            0      100038
11      12            0      100038
12      13            0      100038
13      14            0      100038
14      15            0      100038
15      16            0      100038
16      17            0      100038
17      18            0      100038
18      19            0      100038
19      20            0      100038
20      21            0      100038
21      22            0      100038
22      23            0      100038
23      24            0      100038
24      25            0      100038
25      26            0      100038
26      27            0      100038
27      28            0      100038
28      29            0      100038
29      30            0      100038
30      31            0      100038

[31 rows x 43 columns]
    Hour     HR  O2Sat  Temp    SBP    MAP   DBP  Resp  EtCO2  BaseExcess  \

In [175]:
dataset.to_csv("/Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_3_dataset.csv", index=False)

In [216]:
dataset = pd.read_csv("/Users/rishabkhuba/Documents/MLOps_Project/IE7374-Sepsis-Classification/notebooks/batch_2_dataset.csv")

In [217]:
dataset["SepsisLabel"].value_counts()

0    3904
1      35
Name: SepsisLabel, dtype: int64

In [218]:
dataset.shape

(3939, 43)

In [219]:
dataset.columns

Index(['Hour', 'HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2',
       'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2', 'AST', 'BUN',
       'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct',
       'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium',
       'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC',
       'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2',
       'HospAdmTime', 'ICULOS', 'SepsisLabel', 'Patient_ID'],
      dtype='object')

In [220]:
def data_preprocess_pipeline(df):

    """
    Load, preprocess, and save the dataframe.

    Args:
        Dataframe (pd.DataFrame): dataframe with features and target
    Return:
        Dataframe (pd.DataFrame): X preprocessed dataframe containing features is returned  
        Dataframe (pd.DataFrame): y series returned  
    """

    try:

        # Define columns to drop initially and after preprocessing
        initial_columns_to_drop = ['SBP', 'DBP', 'EtCO2', 'BaseExcess', 'HCO3',
                                   'pH', 'PaCO2', 'Alkalinephos', 'Calcium',
                                   'Magnesium', 'Phosphate', 'Potassium', 'PTT',
                                   'Fibrinogen', 'Unit1', 'Unit2']
        columns_with_high_nulls = ['TroponinI', 'Bilirubin_direct', 'AST', 'Bilirubin_total',
                                   'Lactate', 'SaO2', 'FiO2', 'Unit', 'Patient_ID']
        columns_to_normalize = ['MAP', 'BUN', 'Creatinine', 'Glucose', 'WBC', 'Platelets']
        
        # Create 'Unit' column from 'Unit1' and 'Unit2'
        df["Unit"] = df["Unit1"] + df["Unit2"]

        # Drop initial redundant columns
        df.drop(columns=initial_columns_to_drop, inplace=True)

        # Group by 'Patient_ID' and fill missing values
        df = df.groupby('Patient_ID').apply(lambda x: x.bfill().ffill()).reset_index(drop=True)

        # Drop columns with more than 25% null values
        df.drop(columns=columns_with_high_nulls, inplace=True)

        # Apply log transformation to normalize specific columns
        df[columns_to_normalize] = df[columns_to_normalize].apply(np.log1p)

        # One-hot encode the 'Gender' column
        df['gender'] = df['Gender'].replace({1: 'M', 0: 'F'}).apply(lambda x: x if x in ['M', 'F'] else np.nan)
        encoded_gender = pd.get_dummies(df["gender"])
        df = df.join(encoded_gender).drop(columns=["Gender", "gender"])

        # Ensure the encoded columns are integers
        df['F'] = df['F'].astype(int)
        df['M'] = df['M'].astype(int)

        # Drop remaining rows with any NaN values
        df.dropna(inplace=True)

        # Split the DataFrame back into X and y
        X_preprocessed = df.drop(columns=['SepsisLabel'])
        y_preprocessed = df['SepsisLabel']

        # Remove unwanted columns
        X_preprocessed = X_preprocessed.loc[:, ~X_preprocessed.columns.str.contains('^Unnamed', case=False, regex=True)]
        X_preprocessed.drop(columns=['Hour'], inplace=True)

        # Display shape and value counts for debugging
        print(f"Shape of X after preprocessing: {X_preprocessed.shape}")
        print(f"Shape of y after preprocessing: {y_preprocessed.shape}")
    
        return X_preprocessed, y_preprocessed
        
    except KeyError as ke:
        print("KeyError during preprocessing: %s", ke)
    except ValueError as ve:
        print("ValueError during preprocessing: %s", ve)
    except Exception as ex:
        print("An unexpected error occurred during preprocessing: %s", ex)
        raise

In [221]:
dataset.head()

,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,100,0,0.0,1.0,-167.85,1,0,100078
1,1,57.5,96.5,NaN,159.0,74.5,43.0,16.0,NaN,NaN,...,NaN,NaN,100,0,0.0,1.0,-167.85,2,0,100078
2,2,54.0,98.0,NaN,156.0,99.0,69.0,20.0,NaN,NaN,...,NaN,NaN,100,0,0.0,1.0,-167.85,3,0,100078
3,3,61.0,97.0,NaN,166.0,107.0,74.0,18.0,NaN,NaN,...,NaN,NaN,100,0,0.0,1.0,-167.85,4,0,100078
4,4,58.0,NaN,36.1,160.0,99.0,69.0,16.0,NaN,NaN,...,NaN,NaN,100,0,0.0,1.0,-167.85,5,0,100078

In [222]:
dataset.isna().sum()

Hour                   0
HR                   425
O2Sat                557
Temp                2572
SBP                  458
MAP                  486
DBP                  460
Resp                 872
EtCO2               3595
BaseExcess          3939
HCO3                3937
FiO2                3865
pH                  3867
PaCO2               3868
SaO2                3879
AST                 3867
BUN                 3718
Alkalinephos        3867
Calcium             3679
Chloride            3924
Creatinine          3718
Bilirubin_direct    3929
Glucose             3032
Lactate             3891
Magnesium           3738
Phosphate           3818
Potassium           3650
Bilirubin_total     3867
TroponinI           3856
Hct                 3716
Hgb                 3714
PTT                 3895
WBC                 3722
Fibrinogen          3921
Platelets           3723
Age                    0
Gender                 0
Unit1               1204
Unit2               1204
HospAdmTime            0
ICULOS                 0
SepsisLabel            0
Patient_ID             0
dtype: int64

In [223]:
dataset.shape

(3939, 43)

In [224]:
dataset["Gender"].value_counts()

1    2136
0    1803
Name: Gender, dtype: int64

In [225]:
X, y = data_preprocess_pipeline(dataset)

Shape of X after preprocessing: (211, 18)
Shape of y after preprocessing: (211,)
0    211
Name: SepsisLabel, dtype: int64
Hour           0
HR             0
O2Sat          0
Temp           0
MAP            0
Resp           0
BUN            0
Chloride       0
Creatinine     0
Glucose        0
Hct            0
Hgb            0
WBC            0
Platelets      0
Age            0
HospAdmTime    0
ICULOS         0
SepsisLabel    0
F              0
M              0
dtype: int64

/var/folders/5j/rksnclcn09j1c7_n7bc6nmhr0000gn/T/ipykernel_61733/814224912.py:31: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df = df.groupby('Patient_ID').apply(lambda x: x.bfill().ffill()).reset_index(drop=True)

In [228]:
y.shape

(211,)

In [229]:
X.shape

(211, 18)

In [230]:
y.value_counts()

0    211
Name: SepsisLabel, dtype: int64

In [231]:
def scale_test_data(X, scalar_path):
    """
    Load, scale, and save the test data using the pre-fitted scaler.

    The function:
    - Loads the processed test data from a pickle file.
    - Loads the scaler object from a pickle file.
    - Scales specified columns using the pre-fitted StandardScaler.
    - Saves the scaled test data to a pickle file.
    """
    try:
        scaler = load_data_from_pickle(scalar_path)
        columns_to_scale = ['HR', 'O2Sat', 'Temp', 'MAP', 'Resp', 'BUN', 'Chloride', 'Creatinine', 'Glucose', 'Hct', 'Hgb', 'WBC', 'Platelets']
        X[columns_to_scale] = scaler.transform(X[columns_to_scale])
        
        return X
        
    except FileNotFoundError as e:
        print(f"File not found: {e.filename}. Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during scaling the test data: {e}")

In [232]:
X_scaled = scale_test_data(X, scalar_path)

In [233]:
X_scaled.head()

,HR,O2Sat,Temp,MAP,Resp,BUN,Chloride,Creatinine,Glucose,Hct,Hgb,WBC,Platelets,Age,HospAdmTime,ICULOS,F,M
591,-0.294151,-0.535999,-0.990106,-0.269262,-0.522985,1.076162,-0.220762,1.060382,0.107488,-0.348354,-0.467467,0.206725,-0.617431,65,-211.64,1,0,1
592,-0.294151,-0.535999,-0.990106,-0.269262,-0.522985,1.076162,-0.220762,1.060382,0.107488,-0.348354,-0.467467,0.206725,-0.617431,65,-211.64,2,0,1
593,-0.001158,0.560823,-1.124897,0.080189,-0.522985,1.076162,-0.220762,1.060382,-0.048148,-0.348354,-0.467467,0.206725,-0.617431,65,-211.64,3,0,1
594,0.350433,-0.065932,-1.192293,-0.839747,0.121576,1.076162,-0.220762,1.060382,-0.267911,-0.348354,-0.467467,0.206725,-0.617431,65,-211.64,4,0,1
595,0.555528,0.247445,-1.192293,-1.085908,0.766138,1.076162,-0.220762,1.180807,-0.503526,-1.844390,-1.987247,-0.704575,-1.327282,65,-211.64,5,0,1

In [234]:
print(X_scaled.shape, y.shape)

(211, 18) (211,)

In [235]:
y.value_counts()

0    211
Name: SepsisLabel, dtype: int64

In [236]:
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

def predict(X_scaled, y, model_path):

    # print(model_path)
    # print("X_scaled head:")
    # print(X_scaled.head())
    
    # Load the model
    model = load_data_from_pickle(model_path)
    
    # Predict
    predictions = model.predict(X_scaled)
    
    # Calculate and print metrics
    accuracy = accuracy_score(y, predictions)
    precision = precision_score(y, predictions, average='weighted')
    recall = recall_score(y, predictions, average='weighted')
    f1 = f1_score(y, predictions, average='weighted')
    conf_matrix = confusion_matrix(y, predictions)
    class_report = classification_report(y, predictions)
    
    print(f'Accuracy: {accuracy}')
    print(f'Precision: {precision}')
    print(f'Recall: {recall}')
    print(f'F1 Score: {f1}')
    print(f"\nConfusion Matrix:\n{conf_matrix}")
    print(f"\nClassification Report:\n{class_report}")
    
    return predictions

In [63]:
y_pred = predict(X_scaled, y, model_path)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Confusion Matrix:
[[211]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       211

    accuracy                           1.00       211
   macro avg       1.00      1.00      1.00       211
weighted avg       1.00      1.00      1.00       211